#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Obtener la rama actual
current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$current_branch" = "main" ]; then
  echo "🚫 [POLÍTICA DE SEGURIDAD] Rama MAIN detectada."
  echo "🔍 Buscando console.log prohibidos..."
  npm run lint
else
  echo "⚠️ [MODO DESARROLLO] Rama $current_branch detectada. Logs permitidos."
  exit 0
fi